name: aegis_docs
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  file_picker: ^10.2.0
  file_saver: ^0.3.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^16.0.0
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  mime: ^2.0.0
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfx: ^2.9.2
  permission_handler: ^12.0.1
  pointycastle: ^3.9.1
  reorderable_grid_view: ^2.2.8
  riverpod_annotation: ^2.6.1
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdf: ^30.1.40
  syncfusion_flutter_pdfviewer: ^30.1.41
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  local_auth_android: any
  local_auth_darwin: any
  local_auth_windows: any
  mockito: ^5.4.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
